=== namduongit/nbfc-gui/nbfc-linux/tools/FanControlConfigV3-v1.0.0-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$description": "Schema for nbfc-linux for controlling fans of notebooks",
  "type": "object",
  "properties": {
    "SelectedConfigId": {
      "type": "string",
      "description": "The selected config model. This equals the basename of a notebook model configuration file.",
      "default": ""
    },
    "LegacyTemperatureThresholdsBehaviour": {
      "type": "boolean",
      "description": "Backwards compatibilty with configuration files from the original NBFC project. The default is false. Do not use this option for new configuration files.",
      "default": false,
      "enum": [true, false]
    },
    "EmbeddedControllerType": {
      "type": "string",
      "description": "The preferred way of running nbfc. If not given, the embedded controller type will be automatically selected.",
      "default": "",
      "anyOf": [
        {
          "const": "ec_sys",
          "description": "Use the ec_sys kernel module for writing to the embedded controller."
        },
        {
          "const": "acpi_ec",
          "description": "Use the acpi_ec kernel module for writing to the embedded controller."
        },
        {
          "const": "dev_port",
          "description": "Write to the embedded controller using /dev/port."
        },
        {
          "const": "dummy",
          "description": "Don't write to the embedded controller at all."
        },
        {
          "const": "",
          "description": "The embedded controller type will be automatically selected."
        }
      ]
    },
    "NotebookModel": {
      "type": "string",
      "description": "The Notebook Model as described in your BIOS. See `sudo dmidecode -s system-product-name`."
    },
    "Author": {
      "type": "string",
      "description": "The Author of the config file. Enter whatever you want.",
      "default": ""
    },
    "EcPollInterval": {
      "type": "integer",
      "description": "Defines how often NBFC polls the EC for changes (in miliseconds).",
      "default": "3000",
      "minimum": 1,
      "maximum": 32768
    },
    "ReadWriteWords": {
      "type": "boolean",
      "description": "If `true`, NBFC will combine two 8 bit registers to one 16-bit register when reading from or writing to the EC registers.",
      "default": false,
      "enum": [true, false]
    },
    "CriticalTemperature": {
      "type": "integer",
      "description": "If the temperature exceeds this threshold, NBFC will ignore all Temperature threshold elements and set the fan to 100% speed until the temperature drops below (`CriticalTemperature` - `CriticalTemperatureOffset`)",
      "default": 75,
      "minimum": 0,
      "maximum": 100
    },
    "CriticalTemperatureOffset": {
      "type": "integer",
      "description": "See `CriticalTemperature`",
      "default": 15,
      "minimum": 32768
    },
    "TargetFanSpeeds": {
      "type": "array",
      "description": "This holds the fixed speed of the fans. A value of -1 means the fan should be left in auto mode.",
      "minProperties": 0,
      "items": [
        {
          "type": "integer",
          "minimum": -1,
          "maximum": 65535
        }
      ]
    },
    "FanConfigurations": {
      "type": "array",
      "description": "Array of at least one FanConfiguration",
      "minProperties": 1,
      "items": {
        "type": "object",
        "title": "FanConfiguration",
        "description": "Defines how NBFC controls a fan",
        "properties": {
          "ReadRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register from which NBFC reads the fan speed."
          },
          "WriteRegister": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which NBFC uses to control the fan"
          },
          "MinSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the lowest possible speed (usually this stops the fan). Must be an integer between 0 and 255 or 0 and 65535 if ReadWriteWords is `true`. Note: MinSpeedValue does not necessarily have to be smaller than MaxSpeedValue"
          },
          "MaxSpeedValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which puts the fan to the highest possible fan speed."
          },
          "IndependentReadMinMaxValues": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if independent minimum/maximum values should be applied for read operations"
          },
          "MinSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which corresponds to the lowest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "MaxSpeedValueRead": {
            "$ref": "#/$defs/uword",
            "description": "The value which  corresponds to the highest possible fan speed. Will be ignored if IndependentReadMinMaxValues is `false`."
          },
          "ResetRequired": {
            "type": "boolean",
            "default": false,
            "enum": [true, false],
            "description": "Defines if the EC should be reset before the service is shut down."
          },
          "FanSpeedResetValue": {
            "$ref": "#/$defs/uword",
            "description": "Defines the value which will be written to WriteRegister to reset the EC."
          },
          "FanDisplayName": {
            "type": "string",
            "description": "Fan display name",
            "default": ""
          },
          "TemperatureThresholds": {
            "type": "array",
            "description": "Defines how fast the fan runs at different temperatures",
            "items": {
              "type": "object",
              "properties": {
                "UpThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next upper threshold as soon as the temperature exceeds *UpThreshold*. in celsius"
                },
                "DownThreshold": {
                  "$ref": "#/$defs/ubyte",
                  "description": "NBFC will select the next lower threshold as soon as the temperature falls below the *DownThreshold*. in celsius"
                },
                "FanSpeed": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                }
              },
              "required": ["UpThreshold", "DownThreshold", "FanSpeed"]
            }
          },
          "FanSpeedPercentageOverrides": {
            "type": "array",
            "description": "Overrides the default algorithm to calculate fan speeds",
            "items": {
              "type": "object",
              "properties": {
                "FanSpeedPercentage": {
                  "$ref": "#/$defs/percentage",
                  "description": "The fan speed in percent"
                },
                "FanSpeedValue": {
                  "$ref": "#/$defs/uword",
                  "description": "Fan speed value which will be written to WriteRegister"
                },
                "TargetOperation": {
                  "type": "string",
                  "default": "ReadWrite",
                  "anyOf": [
                    {
                      "const": "Read",
                      "description": "Value->Percentage"
                    },
                    {
                      "const": "Write",
                      "description": "Percentage->Value"
                    },
                    {
                      "const": "ReadWrite",
                      "description": "both"
                    }
                  ],
                  "description": "Defines for which operations the speeds should be overridden."
                }
              }
            }
          }
        },
        "required": [
          "ReadRegister",
          "WriteRegister",
          "MinSpeedValue",
          "MaxSpeedValue",
          "IndependentReadMinMaxValues",
          "MinSpeedValueRead",
          "MaxSpeedValueRead",
          "ResetRequired",
          "FanSpeedResetValue",
          "FanDisplayName",
          "TemperatureThresholds",
          "FanSpeedPercentageOverrides"
        ]
      }
    },
    "RegisterWriteConfigurations": {
      "type": "array",
      "description": "Allows to write to any EC register",
      "items": {
        "type": "object",
        "properties": {
          "WriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "Defines how the value will be written"
          },
          "WriteOccasion": {
            "type": "string",
            "description": "Defines when the value should be written",
            "default": "OnInitialization",
            "anyOf": [
              {
                "const": "OnInitialization",
                "description": "writes the value once upon initialization (everytime the fan control service is enabled or a config is applied)"
              },
              {
                "const": "OnWriteFanSpeed",
                "description": "writes the value everytime the fan speed is set."
              }
            ]
          },
          "Register": {
            "$ref": "#/$defs/ubyte",
            "description": "The register which will be manipulated."
          },
          "Value": {
            "$ref": "#/$defs/uword",
            "description": "The Value which will be written"
          },
          "ResetRequired": {
            "type": "boolean",
            "description": "Defines if the register should be reset before the service is shut down.",
            "enum": [true, false],
            "default": false
          },
          "ResetValue": {
            "$ref": "#/$defs/uword",
            "description": "The value which will be written upon reset."
          },
          "ResetWriteMode": {
            "$ref": "#/$defs/writeModeDef",
            "description": "See WriteMode. Will only be applied on reset"
          },
          "Description": {
            "type": "string",
            "description": "A description of what effect the RegisterWriteConfiguration will have",
            "default": ""
          }
        },
        "required": [
          "WriteMode",
          "WriteOccasion",
          "Register",
          "Value",
          "ResetRequired",
          "ResetValue",
          "ResetWriteMode",
          "Description"
        ]
      }
    }
  },
  "required": [
    "NotebookModel",
    "Author",
    "EcPollInterval",
    "ReadWriteWords",
    "CriticalTemperature",
    "FanConfigurations",
    "RegisterWriteConfigurations"
  ],
  "$defs": {
    "writeModeDef": {
      "type": "string",
      "default": "Set",
      "anyOf": [
        {
          "const": "And",
          "description": "register = register bitwise_and value"
        },
        {
          "const": "Or",
          "description": "register = register bitwise_or value"
        },
        {
          "const": "Set",
          "description": "register = value"
        }
      ]
    },
    "ubyte": {
      "type": "integer",
      "minimum": 0,
      "maximum": 255
    },
    "percentage": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 100.0
    },
    "uword": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    }
  }
}

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/HP Victus 15-fb0xxx.json
{
    
   "NotebookModel": "HP Victus 15-fb0xxx",
   "Author": "subhojit131",
   "EcPollInterval": 1000,
   "ReadWriteWords": false,
   "CriticalTemperature": 85,
   "FanConfigurations": [
      {
       "ReadRegister": 179,
       "WriteRegister": 45,
       "MinSpeedValue": 0,
       "MaxSpeedValue": 100,
       "IndependentReadMinMaxValues": true,
       "MinSpeedValueRead": 0,
       "MaxSpeedValueRead": 21,
       "ResetRequired": true,
       "FanSpeedResetValue": 255,
       "FanDisplayName": "Fan1",
       "Sensors": ["@CPU","@GPU"],
       "TemperatureAlgorithmType": "Max",
       "TemperatureThresholds": [
        {
         "UpThreshold": 0,
         "DownThreshold": 0,
         "FanSpeed": 0.0
        },
        {
         "UpThreshold": 55,
         "DownThreshold": 45,
         "FanSpeed": 10.0
        },
        {
         "UpThreshold": 63,
         "DownThreshold": 55,
         "FanSpeed": 20.0
        },
        {
         "UpThreshold": 68,
         "DownThreshold": 63,
         "FanSpeed": 50.0
        },
        {
         "UpThreshold": 71,
         "DownThreshold": 68,
         "FanSpeed": 70.0
        },
        {
         "UpThreshold": 79,
         "DownThreshold": 71,
         "FanSpeed": 80.0
        },
        {
         "UpThreshold": 82,
         "DownThreshold": 79,
         "FanSpeed": 100.0
        }
       ],
       "FanSpeedPercentageOverrides": [
        {
         "FanSpeedPercentage": 0.0,
         "FanSpeedValue": 255,
         "TargetOperation": "Write"
        }
       ]
      },
      {
       "ReadRegister": 177,
       "WriteRegister": 44,
       "MinSpeedValue": 0,
       "MaxSpeedValue": 100,
       "IndependentReadMinMaxValues": true,
       "MinSpeedValueRead": 0,
       "MaxSpeedValueRead": 21,
       "ResetRequired": true,
       "FanSpeedResetValue": 255,
       "FanDisplayName": "Fan2",
       "Sensors": ["@CPU","@GPU"],
       "TemperatureAlgorithmType": "Max",
       "TemperatureThresholds": [
         {
            "UpThreshold": 0,
            "DownThreshold": 0,
            "FanSpeed": 0.0
           },
           {
            "UpThreshold": 55,
            "DownThreshold": 45,
            "FanSpeed": 10.0
           },
           {
            "UpThreshold": 63,
            "DownThreshold": 55,
            "FanSpeed": 20.0
           },
           {
            "UpThreshold": 68,
            "DownThreshold": 63,
            "FanSpeed": 50.0
           },
           {
            "UpThreshold": 71,
            "DownThreshold": 68,
            "FanSpeed": 70.0
           },
           {
            "UpThreshold": 79,
            "DownThreshold": 71,
            "FanSpeed": 80.0
           },
           {
            "UpThreshold": 82,
            "DownThreshold": 79,
            "FanSpeed": 100.0
           }
       ],
       "FanSpeedPercentageOverrides": [
        {
         "FanSpeedPercentage": 0.0,
         "FanSpeedValue": 255,
         "TargetOperation": "Write"
        }
       ]
      }
   ],
   "RegisterWriteConfigurations": []
  }

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/Asus Zenbook Pro UX550VD.json
{
 "NotebookModel": "Asus Zenbook Pro UX550VD",
 "Author": "rustyx",
 "EcPollInterval": 200,
 "ReadWriteWords": false,
 "CriticalTemperature": 85,
 "FanConfigurations": [
	{
	 "ReadRegister": 151,
	 "WriteRegister": 151,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 8,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 8,
	 "FanDisplayName": "Left Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 41,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 47,
	   "DownThreshold": 38,
	   "FanSpeed": 12.5
	  },
	  {
	   "UpThreshold": 51,
	   "DownThreshold": 46,
	   "FanSpeed": 25.0
	  },
	  {
	   "UpThreshold": 55,
	   "DownThreshold": 50,
	   "FanSpeed": 37.5
	  },
	  {
	   "UpThreshold": 62,
	   "DownThreshold": 54,
	   "FanSpeed": 50
	  },
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 59,
	   "FanSpeed": 62.5
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 63,
	   "FanSpeed": 75
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 67,
	   "FanSpeed": 87.5
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 72,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	},
	{
	 "ReadRegister": 152,
	 "WriteRegister": 152,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 8,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 8,
	 "FanDisplayName": "Right Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 46,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 51,
	   "DownThreshold": 43,
	   "FanSpeed": 12.5
	  },
	  {
	   "UpThreshold": 54,
	   "DownThreshold": 49,
	   "FanSpeed": 25.0
	  },
	  {
	   "UpThreshold": 57,
	   "DownThreshold": 51,
	   "FanSpeed": 37.5
	  },
	  {
	   "UpThreshold": 62,
	   "DownThreshold": 54,
	   "FanSpeed": 50
	  },
	  {
	   "UpThreshold": 66,
	   "DownThreshold": 59,
	   "FanSpeed": 62.5
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 63,
	   "FanSpeed": 75
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 67,
	   "FanSpeed": 87.5
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 72,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 160,
	 "Value": 8,
	 "ResetRequired": true,
	 "ResetValue": 8,
	 "ResetWriteMode": "Set",
	 "Description": "Left FAN"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 166,
	 "Value": 8,
	 "ResetRequired": true,
	 "ResetValue": 8,
	 "ResetWriteMode": "Set",
	 "Description": "Right FAN"
	}
 ]
}

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/HP Laptop 15s-eq3xxx.json
{
  "NotebookModel": "HP Laptop 15s-eq3xxx",
  "Author": "Maru",
  "EcPollInterval": 100,
  "ReadWriteWords": false,
  "CriticalTemperature": 85,
  "CriticalTemperatureOffset": 5,
  "FanConfigurations": [
    {
      "ReadRegister": 46,
      "WriteRegister": 44,
      "MinSpeedValue": 20,
      "MaxSpeedValue": 100,
      "IndependentReadMinMaxValues": false,
      "MinSpeedValueRead": 0,
      "MaxSpeedValueRead": 0,
      "ResetRequired": false,
      "FanSpeedResetValue": 255,
      "FanDisplayName": "CPU Fan",
      "TemperatureThresholds": [
	{
          "UpThreshold": 50,
          "DownThreshold": 40,
          "FanSpeed": 0
        },
        {
          "UpThreshold": 60,
          "DownThreshold": 50,
          "FanSpeed": 30
        },
	{
          "UpThreshold": 70,
          "DownThreshold": 60,
          "FanSpeed": 40
        },
        {
          "UpThreshold": 80,
          "DownThreshold": 70,
          "FanSpeed": 60
        },
	{
	  "UpThreshold": 85,
	  "DownThreshold": 80,
	  "FanSpeed": 90
	}
      ],
      "FanSpeedPercentageOverrides": [
        {
          "FanSpeedPercentage": 100.0,
          "FanSpeedValue": 100,
          "TargetOperation": "ReadWrite"
        }
      ]
    }
  ],
  "RegisterWriteConfigurations": [
    {
      "WriteMode": "Set",
      "WriteOccasion": "OnInitialization",
      "Register": 44,
      "Value": 20,
      "ResetRequired": true,
      "ResetValue": 255,
      "ResetWriteMode": "Set",
      "Description": "Override"
    }
  ]
}

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/Lenovo ThinkPad T14 Gen2.json
{
 "NotebookModel": "LENOVO 20W000Q4GE",
 "Author": "lutzseba",
 "EcPollInterval": 3000,
 "ReadWriteWords": false,
 "CriticalTemperature": 97,
 "FanConfigurations": [
	{
	 "ReadRegister": 47,
	 "WriteRegister": 47,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 7,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 128,
	 "FanDisplayName": "System Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 0,
	   "FanSpeed": 0.0
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 55,
	   "FanSpeed": 20.1970444
	  },
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 60,
	   "FanSpeed": 40.0
	  },
	  {
	   "UpThreshold": 80,
	   "DownThreshold": 65,
	   "FanSpeed": 60.0000038
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 72,
	   "FanSpeed": 80.0
	  },
	  {
	   "UpThreshold": 97,
	   "DownThreshold": 78,
	   "FanSpeed": 100.0
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": []
}

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/Gigabyte Aero15x v8.json
{
 "NotebookModel": "Gigabyte Aero 15x v8",
 "Author": "maximmaxim345",
 "EcPollInterval": 500,
 "ReadWriteWords": false,
 "CriticalTemperature": 95,
 "FanConfigurations": [
	{
	 "ReadRegister": 176,
	 "WriteRegister": 176,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 229,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 19,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 60,
	   "FanSpeed": 50
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 60,
	   "FanSpeed": 55
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 55,
	   "FanSpeed": 80.35
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 55,
	   "FanSpeed": 100
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	},
	{
	 "ReadRegister": 176,
	 "WriteRegister": 177,
	 "MinSpeedValue": 0,
	 "MaxSpeedValue": 229,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 19,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "GPU fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 60,
	   "DownThreshold": 0,
	   "FanSpeed": 0
	  },
	  {
	   "UpThreshold": 65,
	   "DownThreshold": 60,
	   "FanSpeed": 50
	  },
	  {
	   "UpThreshold": 70,
	   "DownThreshold": 60,
	   "FanSpeed": 55
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 55,
	   "FanSpeed": 80.35
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 55,
	   "FanSpeed": 100
	  }
	 ],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 6,
	 "Value": 27,
	 "ResetRequired": true,
	 "ResetValue": 11,
	 "ResetWriteMode": "Set",
	 "Description": "Set custom fan mode type to 'fixed speed'"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 8,
	 "Value": 0,
	 "ResetRequired": false,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Disable quiet mode"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 12,
	 "Value": 161,
	 "ResetRequired": false,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Disable gaming mode"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnInitialization",
	 "Register": 13,
	 "Value": 128,
	 "ResetRequired": true,
	 "ResetValue": 0,
	 "ResetWriteMode": "Set",
	 "Description": "Set custom mode on"
	}
 ]
}

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/HP Laptop 15s-fq5xxx.json
{
 "NotebookModel": "HP Laptop 15s-fq5xxx",
 "Author": "CarlosGS",
 "EcPollInterval": 2000,
 "ReadWriteWords": false,
 "CriticalTemperature": 95,
 "FanConfigurations": [
	{
	 "ReadRegister": 177,
	 "WriteRegister": 244,
	 "MinSpeedValue": 51,
	 "MaxSpeedValue": 64,
	 "IndependentReadMinMaxValues": true,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 20,
	 "ResetRequired": true,
	 "FanSpeedResetValue": 0,
	 "FanDisplayName": "Fan",
	 "TemperatureThresholds": [
	  {
	   "UpThreshold": 75,
	   "DownThreshold": 0,
	   "FanSpeed": 0
	  },
	  {
	   "UpThreshold": 85,
	   "DownThreshold": 40,
	   "FanSpeed": 1
	  },
	  {
	   "UpThreshold": 90,
	   "DownThreshold": 50,
	   "FanSpeed": 85
	  },
	  {
	   "UpThreshold": 95,
	   "DownThreshold": 60,
	   "FanSpeed": 100
	  }
	 ],
	 "FanSpeedPercentageOverrides": [
	  {
	   "FanSpeedPercentage": 0,
	   "FanSpeedValue": 2,
	   "TargetOperation": "Write"
	  }
	 ]
	}
 ],
 "RegisterWriteConfigurations": []
}

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/GPD Win 2 (8100y).json
{
 "LegacyTemperatureThresholdsBehaviour": true,
 "NotebookModel": "GPD Win 2 (8100y)",
 "Author": "Olav Sortland Thoresen",
 "EcPollInterval": 5000,
 "ReadWriteWords": false,
 "CriticalTemperature": 75,
 "FanConfigurations": [
	{
	 "ReadRegister": 52,
	 "WriteRegister": 52,
	 "MinSpeedValue": 33,
	 "MaxSpeedValue": 79,
	 "IndependentReadMinMaxValues": false,
	 "MinSpeedValueRead": 0,
	 "MaxSpeedValueRead": 0,
	 "ResetRequired": false,
	 "FanSpeedResetValue": 127,
	 "FanDisplayName": "CPU fan",
	 "TemperatureThresholds": [
		{
		 "UpThreshold": 0,
		 "DownThreshold": 0,
		 "FanSpeed": 0.0
		},
		{
		 "UpThreshold": 60,
		 "DownThreshold": 48,
		 "FanSpeed": 10.0
		},
		{
		 "UpThreshold": 63,
		 "DownThreshold": 55,
		 "FanSpeed": 20.0
		},
		{
		 "UpThreshold": 66,
		 "DownThreshold": 59,
		 "FanSpeed": 50.0
		},
		{
		 "UpThreshold": 68,
		 "DownThreshold": 63,
		 "FanSpeed": 70.0
		},
		{
		 "UpThreshold": 71,
		 "DownThreshold": 67,
		 "FanSpeed": 100.0
		}
	],
	 "FanSpeedPercentageOverrides": []
	}
 ],
 "RegisterWriteConfigurations": [
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 51,
	 "Value": 0,
	 "ResetRequired": true,
	 "ResetValue": 8,
	 "ResetWriteMode": "Set",
	 "Description": "Reset automatic fan control counter high"
	},
	{
	 "WriteMode": "Set",
	 "WriteOccasion": "OnWriteFanSpeed",
	 "Register": 53,
	 "Value": 0,
	 "ResetRequired": true,
	 "ResetValue": 1,
	 "ResetWriteMode": "Set",
	 "Description": "Reset automatic fan control counter low"
	}
 ]
}

=== namduongit/nbfc-gui/nbfc-linux/share/nbfc/configs/Acer Nitro AN515-58.json
{
	"NotebookModel": "Nitro AN515-58",
	"Author": "FosRexx",
	"EcPollInterval": 3000,
	"CriticalTemperature": 90,
	"CriticalTemperatureOffset": 5,
	"ReadWriteWords": true,
	"FanConfigurations": [
		{
			"FanDisplayName": "CPU Fan",
			"ReadRegister": 19,
			"WriteRegister": 55,
			"MinSpeedValue": 0,
			"MaxSpeedValue": 100,
			"MinSpeedValueRead": 0,
			"MaxSpeedValueRead": 7317,
			"IndependentReadMinMaxValues": true,
			"ResetRequired": false,
			"FanSpeedResetValue": 50,
			"TemperatureThresholds": [
				{
					"UpThreshold": 40,
					"DownThreshold": 0,
					"FanSpeed": 0.0
				},
				{
					"UpThreshold": 50,
					"DownThreshold": 40,
					"FanSpeed": 15.0
				},
				{
					"UpThreshold": 60,
					"DownThreshold": 50,
					"FanSpeed": 50.0
				},
				{
					"UpThreshold": 75,
					"DownThreshold": 60,
					"FanSpeed": 75.0
				},
				{
					"UpThreshold": 90,
					"DownThreshold": 75,
					"FanSpeed": 100.0
				}
			],
			"FanSpeedPercentageOverrides": []
		},
		{
			"FanDisplayName": "GPU Fan",
			"ReadRegister": 21,
			"WriteRegister": 58,
			"MinSpeedValue": 0,
			"MaxSpeedValue": 100,
			"MinSpeedValueRead": 0,
			"MaxSpeedValueRead": 7317,
			"IndependentReadMinMaxValues": true,
			"ResetRequired": false,
			"FanSpeedResetValue": 50,
			"TemperatureThresholds": [
				{
					"UpThreshold": 40,
					"DownThreshold": 0,
					"FanSpeed": 0.0
				},
				{
					"UpThreshold": 50,
					"DownThreshold": 40,
					"FanSpeed": 15.0
				},
				{
					"UpThreshold": 60,
					"DownThreshold": 50,
					"FanSpeed": 50.0
				},
				{
					"UpThreshold": 75,
					"DownThreshold": 60,
					"FanSpeed": 75.0
				},
				{
					"UpThreshold": 90,
					"DownThreshold": 75,
					"FanSpeed": 100.0
				}
			],
			"FanSpeedPercentageOverrides": []
		}
	],
	"RegisterWriteConfigurations": [
		{
			"WriteMode": "Set",
			"WriteOccasion": "OnInitialization",
			"Register": 3,
			"Value": 17,
			"ResetRequired": true,
			"ResetValue": 1,
			"ResetWriteMode": "Set",
			"Description": "The 0x03 register must be set to 17/81 to be able to contorl fan speeds/fan speed + battery limit, setting this to 17 by default since people might not want battery limit"
		},
		{
			"WriteMode": "Set",
			"WriteOccasion": "OnInitialization",
			"Register": 34,
			"Value": 12,
			"ResetRequired": true,
			"ResetValue": 4,
			"ResetWriteMode": "Set",
			"Description": "Setting the CPU Fan to Manual Mode on Initialization and setting it to Auto before the service is shutdown"
		},
		{
			"WriteMode": "Set",
			"WriteOccasion": "OnInitialization",
			"Register": 33,
			"Value": 48,
			"ResetRequired": true,
			"ResetValue": 16,
			"ResetWriteMode": "Set",
			"Description": "Setting the GPU Fan to Manual Mode on Initialization and setting it to Auto before the service is shutdown"
		}
	]
}
